import type { Metadata } from "next";
import { Assistant } from 'next/font/google'
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { TooltipProvider } from "@/components/ui/tooltip";

const assistant = Assistant({
  subsets: ['hebrew'],
  weight: ["200", "300", "400", '500', "600", "700", "800"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="en">
      <body
        className={`${assistant.className}`}
      >
        <Toaster />
        <TooltipProvider>
        {children}
        </TooltipProvider>
      </body>
    </html>
  );
}
